@HostAddress = http://localhost:5235

POST {{HostAddress}}/api/todo
Content-Type: application/json

{
  "title": "Estudar Entity Framework Core",
  "description": "Migrations, DbContext e Fluent API",
  "priority": 1,
  "dueDate": "2026-09-10T00:00:00"
}

###
